#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication decomposePar
runParallel $application 8 
runApplication reconstructPar
