#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

for case in 1 2 3 4 5
do

    cd pflegerTest${case}
 
       application=`getApplication`
       runApplication blockMesh
       runApplication $application

    cd ..

done
